{
    "name": "Demo Website Multiple Snippet",
    "category": "Uncategorized",
    "version": "17.0.1.0.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": [
        "demo_portal",
        "website",
    ],
    "data": [
        "views/snippets.xml",
        "templates/website.xml",
    ],
    "website.assets_frontend": [
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_helloworld_static_structure.scss"
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_helloworld_structure.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_individual_item_structure.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_list_show_time_item_structure.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_list_item_structure.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_list_item_structure_generic.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_list_item_structure_double.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_list_item_structure_double_short.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_helloworld_effect.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_individual_item_effect.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_helloworld_feature.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_individual_item_feature.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_helloworld_content.scss",
        "demo_website_multiple_snippet/static/src/scss/demo_website_multiple_snippet_individual_item_content.scss",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_helloworld_structure.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_individual_item_structure.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_list_show_time_item_structure.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_list_item_structure.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_list_item_structure_generic.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_list_item_structure_double.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_list_item_structure_double_short.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_helloworld_effect.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_individual_item_effect.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_helloworld_feature.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_individual_item_feature.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_helloworld_content.animation.js",
        "demo_website_multiple_snippet/static/src/js/website.demo_website_multiple_snippet_individual_item_content.animation.js",
    ],
    "installable": True,
}
